### PR TITLE
Added support for multiple authors

### PR DESCRIPTION
**Pull request by manzanillo**
Hi there,
this PR adds support for multiple authors (as an Array) to the template.
Hopefully, it helps. I haven't changed the name of the author field to authors, but would support the decision to change this.

Best,
Stefan

### CODE REVIEW

**Comment by scttcper** [comment]
@manzanillo hey i've been slacking here, but this seems like a pretty major change if they all have to be arrays. I'll try to get this in with v3 in some way

**Comment by manzanillo** [comment]
@scttcper Sounds good, hopefully it's helpful :-)

**Comment by samleez** [comment]
> @scttcper Sounds good, hopefully, it's helpful :-)

Thank you for such effort bro, Please can you take a look at the issue of Laggy and slow scrolling in this starter? it has to do with the original ghost theme. it will be great if you can fix that

**Comment by valeIT** [comment]
> > @scttcper Sounds good, hopefully, it's helpful :-)
> 
> Thank you for such effort bro, Please can you take a look at the issue of Laggy and slow scrolling in this starter? it has to do with the original ghost theme. it will be great if you can fix that

You should not plug your issue in an unrelated pull request. =) @scttcper will get to it when he has the time

**Pull request merged**
