### PR TITLE
hotfix: filter content where draft is set to 'true'

### PR DESCRIPTION
**Pull request by sebastian-ojeda**
Whenever `draft` is set to `true`, the content should be filtered out. This is in agreement with how [related posts](https://github.com/scttcper/gatsby-casper/blob/1bd4d327741b4a58ba5153448b7aa5c28ced09de/src/templates/post.tsx#L372) are currently implemented.

### CODE REVIEW

**Comment by VictorBaudot** [comment]
I personally did put this filter
```
filter: { frontmatter: { draft: { ne: true } } }
```
in the graphql query in gatsby-node, pages/404 and templates/(author, post, tags)

**Comment by scttcper** [comment]
so you'd need to comment this out to preview a post?

**Comment by TheBryanMac** [comment]
This is a tricky one. Some will want a draft message in their repo, and able to preview - but not in production (most likely). The frontmatter *draft* property isn't needed if not going to filter them out. Maybe a hybrid solution: Hide from gatsby-node, pages/404 and templates/(author, post, tags) as @VictorBaudot mentions as to hide all draft posts from the main flow of the site. But also add a "drafts" page that can show any draft posts:
`site.com/drafts/post-to-review.md`
Just a thought.

**Comment by scttcper** [comment]
ended up changing it to filter at the template level

**Pull request merged**
